version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8888:8888"
    volumes:
      - .:/work
    tty: true
    stdin_open: true
    command: "jupyter-lab --ip 0.0.0.0 --no-browser --allow-root"
